config_path: null
name_or_path: mistralai/Mixtral-8x22B-v0.1
torch_dtype: bfloat16

fsdp_config: 
  fsdp_transformer_layer_cls_to_wrap: ["MixtralDecoderLayer"]
  min_num_params: 0
  xla_fsdp_grad_ckpt: true